In [1]:
import mlrose
import numpy as np
import time

C:\Users\vparihar\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\externals\six.py:31: DeprecationWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", DeprecationWarning)


In [2]:
fitness = mlrose.OneMax()

problem = mlrose.DiscreteOpt(length = 35, fitness_fn = fitness, maximize = True, max_val = 2)

# Define initial state
init_state = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0])


In [3]:
schedule = mlrose.ExpDecay()

In [4]:
# Solve problem using Simulated Annealing
start_time = time.time()
best_state, best_fitness,fitness_curve = mlrose.simulated_annealing(problem, schedule = schedule,
                                                      max_attempts = 100, max_iters = 1000,
                                                      init_state = init_state, random_state = 1 , curve = True)
print("Simulated Annealing time: ",time.time()-start_time)

print(best_state,best_fitness,fitness_curve.size)

Simulated Annealing time:  0.01400136947631836
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 35.0 463


In [5]:
# Solve problem using Random Hill Climbing without restart
start_time =time.time()
best_state, best_fitness,fitness_curve = mlrose.random_hill_climb(problem,max_attempts = 100, max_iters = 1000,
                                                      init_state = init_state, random_state = 1 , curve = True)
print("rhc time without restart: ",time.time()-start_time)

print(best_state,best_fitness,fitness_curve.size)

rhc time without restart:  0.010003328323364258
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 35.0 277


In [6]:
# Solve problem using Random Hill Climbing with restart
start_time =time.time()
best_state, best_fitness,fitness_curve = mlrose.random_hill_climb(problem,max_attempts = 100, max_iters = 1000,
                                                      init_state = init_state, random_state = 1 , restarts =2 ,curve = True)
print("rhc time with restart: ",time.time()-start_time)
print(best_state,best_fitness,fitness_curve.size)

rhc time with restart:  0.02798938751220703
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 35.0 856


In [7]:
# Solve problem using Gentic Algorithm
start_time =time.time()
best_state, best_fitness,fitness_curve = mlrose.genetic_alg(problem, pop_size=200, mutation_prob=0.4, 
                                                            max_attempts=100, max_iters=1000, curve=True, random_state=1)
print("Genetic time: ",time.time()-start_time)
print(best_state,best_fitness,fitness_curve.size)

Genetic time:  2.2757480144500732
[1 1 1 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 30.0 164


In [8]:
# Solve problem using Mimic Fast Algorithm
start_time =time.time()
best_state, best_fitness,fitness_curve = mlrose.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=100, max_iters=1000, curve=True, random_state=1, fast_mimic=True)

print("Mimic Fast time: ",time.time()-start_time)
print(best_state,best_fitness,fitness_curve.size)

Mimic Fast time:  1.3250751495361328
[1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 34.0 104


In [9]:
# Solve problem using Mimic Slow Algorithm
start_time =time.time()
best_state, best_fitness,fitness_curve = mlrose.mimic(problem, pop_size=200, keep_pct=0.2, max_attempts=100, max_iters=1000, curve=True, random_state=1, fast_mimic=False)

print("Mimic Slow time: ",time.time()-start_time)
print(best_state,best_fitness,fitness_curve.size)

Mimic Slow time:  35.61999750137329
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1] 35.0 106
